version: '3'

services:
  database_mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Saddam1209*
      - MYSQL_DATABASE=booknote
    ports:
      - 3306:3306
    container_name: database_mysql
  book_server:
    build:
      context: backend
    ports:
      - 5000:5000
    container_name: book_server
    depends_on:
      - database_mysql
    environment:
      - PORT=5000
      - DATABASE_URL=mysql://root:Saddam1209*@database_mysql/booknote?schema=public
    restart: always
  web_server:
    build:
      context: client
    ports:
      - 80:80
    volumes:
      - ./client/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - book_server
    container_name: web_server
